# syntax=docker/dockerfile:1

FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG API_URL
ENV API_URL=${API_URL}
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ARG NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
ARG NEXT_PUBLIC_AUTH_LOGIN_PATH
ENV NEXT_PUBLIC_AUTH_LOGIN_PATH=${NEXT_PUBLIC_AUTH_LOGIN_PATH}
ARG NEXT_PUBLIC_COMMISSION_PERCENT
ENV NEXT_PUBLIC_COMMISSION_PERCENT=${NEXT_PUBLIC_COMMISSION_PERCENT}
ARG NEXT_PUBLIC_SWAPTRUST_ORANGE_MONEY
ENV NEXT_PUBLIC_SWAPTRUST_ORANGE_MONEY=${NEXT_PUBLIC_SWAPTRUST_ORANGE_MONEY}
ARG NEXT_PUBLIC_SWAPTRUST_WAVE
ENV NEXT_PUBLIC_SWAPTRUST_WAVE=${NEXT_PUBLIC_SWAPTRUST_WAVE}
ARG NEXT_PUBLIC_SWAPTRUST_BANK_IBAN
ENV NEXT_PUBLIC_SWAPTRUST_BANK_IBAN=${NEXT_PUBLIC_SWAPTRUST_BANK_IBAN}
ARG NEXT_PUBLIC_SWAPTRUST_BANK_NAME
ENV NEXT_PUBLIC_SWAPTRUST_BANK_NAME=${NEXT_PUBLIC_SWAPTRUST_BANK_NAME}

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
